services:
  api:
    image: kvitta
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      #dockerfile: Dockerfile
      target: development
    environment:
      - KVITTA_DB_CONNECTION=${KVITTA_DB_CONNECTION}
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - kvitta_db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
volumes:
    kvitta_db: