services:
  kvitta:
    image: kvitta
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: Kvitta/Dockerfile
    environment:
      - POSTGRES_CONNECTION=${POSTGRES_CONNECTION}
    env_file:
      - .env
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - kvitta_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
volumes:
    kvitta_db: