networks:
  kvitta:

volumes:
  kvitta_db:

services:

  api:
    image: kvitta-app
    container_name: kvitta-api
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped
    build:
      context: .
      dockerfile: build
    env_file:
      - .env
    environment:
      - KvittaDbConnection=Host=kvitta-db;Port=5432;Database=${POSTGRES_DATABASE};Username=postgres;Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - kvitta
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16
    container_name: kvitta-db
    ports:
      - "127.0.0.1:54333:5432"
    volumes:
      - kvitta_db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    networks:
      - kvitta
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
