services:
  #  api:
  #    image: kvitta
  #    ports:
  #      - "8080:8080"
  #      - "8081:8081"
  #    restart: on-failure
  #    build:
  #      context: .
  #      dockerfile: build
  #    environment:
  #      - KVITTA_DB_CONNECTION=${KVITTA_DB_CONNECTION}
  #      - ASPNETCORE_ENVIRONMENT=Development
  #    env_file:
  #      - .env
  #    volumes:
  #      - type: volume
  #        source: kvitta-logs
  #        target: /var/logs
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - kvitta_db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    networks:
      - kvitta_network
networks:
  kvitta_network:
    driver: bridge
volumes:
  kvitta_db: